version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    environment:
      PYTHONBUFFERED: 1
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app



  db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vnv_blog
    networks:
      - app


networks:
  app:
    driver: bridge
